name: bilibili

on:
    workflow_dispatch:
    schedule:
        - cron: 10 16 * * *
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: "安装依赖包"
              run: pip3 install -r ./requirements.txt

            - name: "运行 哔哩哔哩签到"
              run: python3 function/bilibili/bilibili.py
              env:
                  BILI_USER: ${{ secrets.BILI_USER }}
                  BILI_PASS: ${{ secrets.BILI_PASS }}
                  BILI_COOKIE: ${{ secrets.BILI_COOKIE }}
                  BILI_NUM: ${{ secrets.BILI_NUM }}
                  BILI_TYPE: ${{ secrets.BILI_TYPE }}
                  SEND_KEY: ${{ secrets.SEND_KEY }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN}}
                  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER}}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
                  QYWX_AM: ${{ secrets.QYWX_AM}}
#最后推送 2021年4月22日