name: zdforum

on:
    workflow_dispatch:
    schedule:
        - cron: 20 16 * * *
    watch:
        types: [started]

jobs:
    build1:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 11.x
              uses: actions/setup-node@v
              with:
                  node-version: 11.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【终点论坛自动签到】"
              run: |
                  node function/zd-forum/zd-forum.js
              env:
                  ZD_USER: ${{ secrets.ZD_USER }}
                  ZD_PASS: ${{ secrets.ZD_PASS}}
                  SEND_KEY: ${{ secrets.SEND_KEY }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN}}
                  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER}}
                  QYWX_KEY: ${{ secrets.QYWX_KEY}}
                  QYWX_AM: ${{ secrets.QYWX_AM}}
                  TG_PROXY_HOST: ${{ secrets.TG_PROXY_HOST}}
                  TG_PROXY_PORT: ${{ secrets.TG_PROXY_PORT}}
                  IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY}}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
#最后推送 2021年4月09日
